### ISSUE TITLE
Table 2 and 3 results

### ISSUE THREAD

**Issue by lucky-23** [quangminhdinh/TrafficVLM#2]
How do I obtain the table 2 and 3 results? I can generate the captions but not the scores.

**Comment by quangminhdinh** [comment]
Hi,
Table 2 and 3 results are obtained by evaluating the main WTS validation set, as it has groundtruth captions. To generate captions for this set, you can set DATA.TEST_DATASETS in the experiment configuration file to { "name": "wts_val_main", "ratio": -1 }. After that, you can evaluate it using the evaluation script provided with the WTS dataset (https://github.com/woven-visionai/wts-dataset/tree/main/evaluation/eval-metrics-AIC-Track2).
